executor: slurm
jobs: 50
use-conda: true
latency-wait: 60
retries: 0
default-resources:
  slurm_partition: "low"
  slurm_account: "publicgrp"
  mem_mb: 2000
  runtime: 5
jobname: "this_jobname_{jobid}"
slurm-keep-successful-logs: true
slurm-logdir: "jobs/"
jobscript: "slurm/jobscript.sh"
conda-frontend: mamba